name: Pylint Debug

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint

    - name: List Python files
      run: |
        FILES=$(git ls-files '*.py')
        echo "=== Python files found ==="
        printf "'%s'\n" $FILES
        echo "=========================="

    - name: Run pylint on each Python file separately
      run: |
        FILES=$(git ls-files '*.py')
        if [ -z "$FILES" ]; then
          echo "No Python files to lint."
        else
          for file in $FILES; do
            echo "Linting $file"
            pylint -- "$file" || echo "File $file caused pylint error"
          done
        fi
