    - name: Install autopep8
      run: pip install autopep8

    - name: Auto fix Python files with autopep8
      run: |
        FILES=$(git ls-files '*.py')
        if [ -n "$FILES" ]; then
          autopep8 --in-place --aggressive --aggressive $FILES
        else
          echo "No Python files to fix."
        fi

    - name: Commit and push changes if any
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if ! git diff --quiet; then
          git add .
          git commit -m "Auto format Python files with autopep8"
          git push
        else
          echo "No changes to commit"
        fi
