name: Update README on Push

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'scripts/update_readme.py'
      - '.github/workflows/update-readme.yml'

permissions:
  contents: write

concurrency:
  group: update-readme-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-readme:
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.actor != 'github-actions[bot]'"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run script to update README
        run: |
          python scripts/update_readme.py

      - name: Commit and push changes (skip ci)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Auto update README [skip ci]"
          git push
